FROM python:3.7-slim

RUN apt update -y
RUN apt install -y git

WORKDIR /home/root/project/

COPY ./backend/requirements.txt ./requirements.txt

# RUN pip3 install -U pip
RUN pip3 install -r requirements.txt --no-cache-dir

# CMD ["gunicorn", "foodgram.wsgi:application", "--bind", "0:8000"]
