version: '3.3'

volumes:
  static_value:
  media_value:
  db_data:

services:
  db:
    image: postgres:14.0-alpine
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env

  # frontend:
  #   build:
  #     context: ../frontend
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ../frontend/:/app/result_build/

  backend:
    build:
      context: .
      dockerfile: Dockerfile_dev
    restart: always
    volumes:
      - ./:/home/root/project
    depends_on:
      - db
    env_file:
      - ./.env
    command: /bin/sh -c "while sleep 1000; do :; done"
