version: '3.3'

volumes:
  static_value:
  media_value:
  db_data:

services:

  backend:
    image: valentinvalter/foodgram_backend:v1.0
    restart: always
    volumes:
      - static_value:/app_back/static/
      - media_value:/app_back/media/
    depends_on:
      - db
    env_file:
      - .env
    container_name: foodgram_backend

  db:
    image: postgres:14.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - .env

  frontend:
    image: valentinvalter/foodgram_frontend:v1.0
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
    container_name: foodgram_frontend

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - backend
    container_name: foodgram_nginx
